import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AcchaNavbar from "@/components/shared/navigation/Navbar";
import Footer from "@/components/shared/navigation/Footer";
import { BusinessChatbot } from "@/components/shared/chat/ChatIcon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Simulate a loading delay
  // You can replace this with your actual loading logic
  // For example, fetching data or waiting for a condition to be met

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-auto flex flex-col justify-center items-center bg-white bg-[url('/bg-pattern.png')] bg-repeat bg-[length:120px_120px] min-h-screen`}
      >


        <div className=" ">
          <AcchaNavbar>{children}</AcchaNavbar>
          <Footer />
        {/* <BusinessChatbot/> */}
        </div>
      </body>
    </html>
  );
}
